//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.000000	14.45
        ///0.055556	14.75
        ///0.111111	14.39
        ///0.166667	14.50
        ///0.222222	12.81
        ///0.277778	12.73
        ///0.333333	12.90
        ///0.388889	12.95
        ///0.444444	12.35
        ///0.500000	10.52
        ///0.555556	9.69
        ///0.611111	9.25
        ///0.666667	8.85
        ///0.722222	8.92
        ///0.777778	8.41
        ///0.833333	8.52
        ///0.888889	8.35
        ///0.944444	8.44
        ///1.000000	8.52
        ///1.055556	8.61
        ///1.111111	8.74
        ///1.166667	8.83
        ///1.222222	8.94
        ///1.277778	9.01
        ///1.333333	9.10
        ///1.388889	9.17
        ///1.444444	9.24
        ///1.500000	9.30
        ///1.555556	9.36
        ///1.611111	9.41
        ///1.666667	9.47
        ///1.722222	9.51
        ///1.777778	9.56
        ///1.833333	9.60
        ///1.888889	9.64
        ///1.944444	9.6 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string calibrationG6009 {
            get {
                return ResourceManager.GetString("calibrationG6009", resourceCulture);
            }
        }
    }
}
